### ISSUE TITLE
Chromedriver CLI Install Command

### ISSUE THREAD

**Issue by jackrabbitbit** [PDXPythonPirates/vaccinewatcher#9]

**Comment by Xuehong-pdx** [comment]
The program freezes now after I pulled this change.  run() invokes no action now.  I checked the driver version and it seems to be correct.

**Comment by jackrabbitbit** [comment]
Really? Chris was on the phone with me walking me through how to use GIT. All we did was add a line to the README, we didn't touch anything else...weird.

**Comment by Xuehong-pdx** [comment]
I don't know what might be changed.  It was working for me earlier today,
then I saw some updates so I pull the changes and now when I do run() it
just sits there.

**Comment by Xuehong-pdx** [comment]
Wow, it might be my internet.  It worked this time.

**Comment by Xuehong-pdx** [comment]
Must be my internet.  It works now.
